### PR TITLE
Drop python 2.7 support and make noarch: python

### PR DESCRIPTION
**Pull request by tschoonj**
Python 2.7 is no longer supported by conda-forge.
Making it noarch also adds automatic support for aarch64 and ppc64le

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by tschoonj** [comment]
I already rerendered, see the second commit.

**Comment by xylar** [comment]
@tschoonj, I've found that local rerenders give glitchy results if the folder you're working from doesn't happen to be named `tenacity-feedstock` (which it never is for me).  So I was just making sure.

Thanks very much for this work!

**Comment by tschoonj** [comment]
Thanks!

**Comment by tschoonj** [comment]
Unfortunately something went wrong when merging this PR in: no build was kicked off on Azure for some reason...

**Pull request merged**
