### PR TITLE
Revert temporarily to 4.12.0 to get a python 3.7 build

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

I will revert these changes once v4.12.0 has built for python 3.7.

### CODE REVIEW

**Comment by xylar** [comment]
This is needed for https://github.com/conda-forge/airflow-feedstock/pull/27

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@sodre, please review at your convenience.

**Comment by sodre** [comment]
@xylar, no need to revert. I think the bot will pick up the next available release when a new version of tenacity is released.

**Comment by xylar** [comment]
Thanks!

**Pull request merged**
